# NUMPY 


In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5],dtype='int32')
print(a)
type(a)

[1 2 3 4 5]


numpy.ndarray

In [3]:
a1=np.array([[1.1,2.2,3.4],[5.6,7.8,9.8]])
print(a1)

[[1.1 2.2 3.4]
 [5.6 7.8 9.8]]


In [4]:
print(a.ndim)
print(a1.ndim)

1
2


In [5]:
a.shape

(5,)

In [6]:
a1.shape

(2, 3)

In [7]:
a.dtype

dtype('int32')

In [8]:
a1.dtype

dtype('float64')

In [9]:
a.itemsize

4

In [10]:
a.size*a.itemsize 

20

In [11]:
a.nbytes

20

In [12]:
a1.size

6

In [13]:
b=np.array([1,2,3,4,5],dtype='int32',ndmin=3)

In [14]:
print(b)
b.ndim

[[[1 2 3 4 5]]]


3

In [15]:
arr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [16]:
arr.shape

(2, 6)

In [17]:
print(arr[1,5])

12


In [18]:
print(arr[1,-1])

12


In [19]:
# get row
print(arr[0,:])

[1 2 3 4 5 6]


In [20]:
print(arr[:,2])

[3 9]


In [21]:
print(arr[0,::2])

[1 3 5]


In [22]:
print(arr[0,:-1:2])  # startindex:endindex:stepsize

[1 3 5]


In [23]:
arr[1,1:4]=0

In [24]:
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  0  0  0 11 12]]


In [25]:
arr[:,0]=[1,10]

In [26]:
print(arr)

[[ 1  2  3  4  5  6]
 [10  0  0  0 11 12]]


In [27]:
arr1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [28]:
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [29]:
print(arr1[0,1,2])

6


In [30]:
arr1[1,1,:]=10

In [31]:
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 10, 10]]])

In [32]:
n=np.ones((5,5),dtype='int32')

In [33]:
print(n)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [34]:
n[1:4,1:4]=0

In [35]:
n

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [36]:
n[2,2]=5

In [37]:
n

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 5, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [38]:
np.zeros((1,2,2))

array([[[0., 0.],
        [0., 0.]]])

In [39]:
np.ones((4,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [40]:
np.full((2,3),99)

array([[99, 99, 99],
       [99, 99, 99]])

In [41]:
np.random.rand(4,2)

array([[0.89804287, 0.10924292],
       [0.97687708, 0.54366636],
       [0.62369144, 0.50749705],
       [0.81018678, 0.93044301]])

In [42]:
np.random.randint(7,size=(2,3))

array([[6, 3, 2],
       [4, 4, 0]], dtype=int32)

In [43]:
a=np.ones((2,3))
b=np.full((3,2),99)

In [44]:
arr=np.array([1,2,3,4,5,0,9,0])

newarr=arr.astype(bool)
print(newarr)

[ True  True  True  True  True False  True False]


In [45]:
arr.shape

(8,)

In [46]:
arr=np.array([1,2,3,4,5,6,7])
newarr=arr[arr%2==0]
print(newarr)

[2 4 6]


In [47]:
a=np.arange(1,31).reshape(1,6,5)

In [48]:
a

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [49]:
b=np.matrix([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]])

In [50]:
b

matrix([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]])

In [51]:
b[[0,4,5],3:]

matrix([[ 4,  5],
        [24, 25],
        [29, 30]])

In [52]:
#digonal element
b[[0,1,2,3,4],[0,1,2,3,4]]

matrix([[ 1,  7, 13, 19, 25]])

In [53]:
b[b%2==0]

matrix([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]])

In [59]:
np.max(b,axis=0)
np.min(b)

np.int64(1)

In [55]:
print(np.where(b==23))

(array([4]), array([2]))


In [56]:
a=np.array([1,2,3,4,56,7,8,9],ndmin=6)

In [57]:
a

array([[[[[[ 1,  2,  3,  4, 56,  7,  8,  9]]]]]])

In [58]:
for i in np.nditer(a):
    print(i)

1
2
3
4
56
7
8
9


In [60]:
a=np.array([1,2,3,4,5,6])
b=a.view() # changes origninal array
c=a.copy() # have copy of array 

In [62]:
b[1]=10
a

array([ 1, 10,  3,  4,  5,  6])

In [66]:
c[1:3]=10
c
a

array([ 1, 10,  3,  4,  5,  6])

In [67]:
print(c.base)

None


In [69]:
print(b.base) # b own the data from a

[ 1 10  3  4  5  6]


In [72]:
a1=([1,2],[3,4])
a2=([5,6],[7,8])

a3=np.concatenate((a1,a2),axis=1) # axis1 ---->> along row
a4=np.concatenate((a1,a2),axis=0)

In [71]:
a3

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [73]:
a4

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [74]:
np.stack((a1,a2),axis=1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [75]:
np.dstack((a1,a2))

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

In [76]:
np.hstack((a1,a2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [77]:
np.vstack((a1,a2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])